#
# This file contains configuration flags to customize your blog
#

# The name of your blog
name: Portfolio Blog | Errin Johnson
# Home Portfolio AlchemyMomentum
alchemyHome: http://alchemymomentum.com
# A short bio or description
description:
 Blog measuring my skills and progress in my Software Development.
# A URL pointing to your avatar or profile pic
# To use your Gravatar: (the one that GitHub uses for your profile pic)
#   1. Go to https://github.com/YOURUSERNAME/
#   2. Right click > Copy Image URL on your profile pic,
#   3. Take the first long ID from the URL and paste it in place of mine below
avatar: https://s3-us-west-2.amazonaws.com/alchemymomentum.com/img/Errin_Profile.JPG

# Your disqus username, if you'd like blog commenting
disqus: 

# Your Google Analytics web tracking code (e.g. UA-2110908-2)
google_analytics: 

# Links used for your social icons
links:
  github: errinjohnson
  #twitter: your-username

markdown: kramdown
pygments: true
permalink: /:title

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - scss
    - README.md
